import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import QueryProvider from "@/hooks/QueryProvider";

export const metadata: Metadata = {
  title: "Looper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <AppRouterCacheProvider>
            <main>{children}</main>
          </AppRouterCacheProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
