import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import QueryProvider from '@/providers/QueryProvider';
import { GoogleAnalytics } from '@next/third-parties/google';
import { PublicEnvScript } from 'next-runtime-env'; // 런타임 변수 주입

export const metadata: Metadata = {
  title: 'Looper',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <PublicEnvScript />
      </head>
      <body>
        <QueryProvider>
          <AppRouterCacheProvider>
            <main>{children}</main>
          </AppRouterCacheProvider>
        </QueryProvider>
        <GoogleAnalytics gaId="G-XDRJBMQXDN" />
      </body>
    </html>
  );
}
